version: '3.3'

services:
  web:
    build:
      context: .
    image: dilan151/my_flask
    ports:
      - '80:80'
    restart: always
    depends_on:
      - db
  db:
    image: postgres
#    ports:
#      - '5433:5332'
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_name
#    ports:
#      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:



